# Generated by Django 2.2.2 on 2019-06-23 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190623_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizzashop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PizzaShop', verbose_name='Пиццерия'),
        ),
    ]
