# Generated by Django 2.2.2 on 2019-06-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190624_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='photo',
            field=models.ImageField(default='', upload_to='app/photos', verbose_name='Фотография'),
        ),
    ]
