# Generated by Django 2.2.2 on 2019-06-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pizza_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
