# Generated by Django 2.2.2 on 2019-07-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190625_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='short_description',
            field=models.CharField(default='', max_length=200, verbose_name='Краткое описание'),
        ),
    ]
