# Generated by Django 2.2.2 on 2019-07-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_pizza_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('short_description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('preview', models.ImageField(default='', upload_to='app/photos', verbose_name='Фотография')),
                ('photo', models.ImageField(default='', upload_to='app/photos', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='PizzaShop',
        ),
    ]
