# Generated by Django 2.2.2 on 2019-07-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190709_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='app/photos', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.ImageField(blank=True, default='', upload_to='app/photos', verbose_name='Фотография'),
        ),
    ]
