# Generated by Django 2.2.2 on 2019-07-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190709_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['id'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Краткое описание'),
        ),
    ]
