# Generated by Django 2.2.3 on 2019-07-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190713_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='code',
            field=models.TextField(blank=True, verbose_name='Пример кода'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.ImageField(blank=True, default='', upload_to='app/photos', verbose_name='Превью'),
        ),
    ]
