# Generated by Django 2.2.3 on 2019-07-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190719_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='code2',
            field=models.TextField(blank=True, verbose_name='Пример кода'),
        ),
    ]
