# Generated by Django 2.2.3 on 2019-08-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190805_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo3',
        ),
        migrations.AddField(
            model_name='news',
            name='slaid_name1',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Название первого слайда'),
        ),
        migrations.AddField(
            model_name='news',
            name='slaid_name2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Название второго слайда'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='app/photos', verbose_name='Первый слайд'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo2',
            field=models.ImageField(blank=True, default='', upload_to='app/photos', verbose_name='Второй слайд'),
        ),
    ]
