# Generated by Django 2.2.3 on 2019-08-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190806_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slaid_name1',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Название первого слайда/Название первого файла с примером кода'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slaid_name2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Название второго слайда/Название второго файла с примером кода'),
        ),
    ]
